### ISSUE TITLE
.form-control-label should only appear in horizontal forms

### ISSUE THREAD

**Issue by troytc** [crslade/bootstrap4-form-builder#1]
According to the [official docs for v4](http://v4-alpha.getbootstrap.com/components/forms/#form-controls), form labels should not have the `.form-control-label` class unless they appear in a horizontal form.  This causes the offset shown below:

---

Using bootstrap4-form-builder:

![Personal Example](https://i.imgur.com/YYud41T.png)

---

Official docs:

![Official Docs Example](https://i.imgur.com/AU2piyJ.png)

**Comment by crslade** [comment]
Thanks, I'll work on a fix, and release a new version soon.

**Comment by crslade** [comment]
I just released a new version, and the form-control-label should not be present unless you are doing a horizontal form.

**Comment by troytc** [comment]
Thanks for the quick fix!  Works perfectly.
